# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

resources:
- repo: self
variables:
- group: dev-var-group
- name: imageRepositoryBackend
  value: 'backend'
- name: imageRepositoryFrontend
  value: 'frontend'
- name: dockerfilePathBackend
  value: '$(Build.SourcesDirectory)/src/backend/Dockerfile'
- name: dockerfilePathFrontend
  value: '$(Build.SourcesDirectory)/src/frontend/Dockerfile'
- name: vmImageName
  value: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepositoryBackend)
        dockerfile: $(dockerfilePathBackend)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
            $(Build.BuildId)

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepositoryFrontend)
        dockerfile: $(dockerfilePathFrontend)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
            $(Build.BuildId)
          
    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'manifests'
        path: '$(Build.SourcesDirectory)'

